# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: iconic-core-db