# docker-compose.yml
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: iconic-core-db
    container_name: mongodb
    
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    container_name: app